#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__
#define RIGHT "right/"
#define DOWN "down/"
#define UP "up/"
#define FIVE_PICTURES 6
#define TWO_PICTURES 3
#define SCRAMBLER_VELOCITY 9
#define THREE 3
#define INITIAL_HEALTH_RUNNER 250
#define INITIAL_HEALTH_STUBBORN 400
#define INITIAL_HEALTH_SUPERTROOPER 500
#define INITIAL_HEALTH_SCRAMBLER 100
#define HEIGHT_BLOOD_BAR 5
#define WIDTH_BLOOD_BAR 40
#define RAISE_HEIGHT 20
#define TOWER_DISTANCE 150
#define MISSILE_DISTANCE 50
#define DEATH 0
#define ALIVE 1
#endif
